// src/components/PrintPreviewModal.tsx
import React, { useRef, useState, useEffect } from 'react';
import { 
  Printer, Scissors, FlipHorizontal, Download, 
  Settings, X, ZoomIn, ZoomOut, Info, Loader2
} from 'lucide-react';
import IDCardPreview from './IDCardPreview';
import { type ApplicantCard } from '../types/card';
import { toast } from 'react-toastify';
import { confirmApplicant } from '../api/students';
import { 
  PRINT_WIDTH, 
  PRINT_HEIGHT 
} from '../constants/dimensions';

interface PrintModalProps {
  data: ApplicantCard;
  layout: any;
  onClose: () => void;
}

interface ExtendedWindow extends Window {
  process?: { type?: string; };
  versions?: { electron?: string; };
}

const PrintPreviewModal: React.FC<PrintModalProps> = ({ data, layout, onClose }) => {
  const [zoom, setZoom] = useState(1.0);
  const [mirrorBack, setMirrorBack] = useState(false);
  const [frontImage, setFrontImage] = useState<string>('');
  const [backImage, setBackImage] = useState<string>('');
  const [isGeneratingImages, setIsGeneratingImages] = useState(true);
  
  // Margin Settings in pixels
  const [marginTop, setMarginTop] = useState(0);
  const [marginBottom, setMarginBottom] = useState(0);
  const [marginLeft, setMarginLeft] = useState(0);
  const [marginRight, setMarginRight] = useState(0);

  const marginPresets = [
    { label: 'None', values: { top: 0, bottom: 0, left: 0, right: 0 } },
    { label: '5px', values: { top: 5, bottom: 5, left: 5, right: 5 } },
    { label: '10px', values: { top: 10, bottom: 10, left: 10, right: 10 } },
  ];

  const applyMarginPreset = (preset: typeof marginPresets[0]) => {
    setMarginTop(preset.values.top);
    setMarginBottom(preset.values.bottom);
    setMarginLeft(preset.values.left);
    setMarginRight(preset.values.right);
  };

  /**
   * Capture High-Res Data from Konva Stages
   * Since IDCardPreview uses react-konva, we extract the dataURL directly from the 
   * internal canvas for maximum accuracy.
   */
  useEffect(() => {
    const captureKonvaStages = async () => {
      setIsGeneratingImages(true);
      
      // Wait for images (photo/signature) to load in the hidden stages
      await new Promise(resolve => setTimeout(resolve, 2000));

      try {
        // Find the actual canvas elements generated by react-konva
        const frontCanvas = document.querySelector('#front-print-stage canvas') as HTMLCanvasElement;
        const backCanvas = document.querySelector('#back-print-stage canvas') as HTMLCanvasElement;

        if (frontCanvas && backCanvas) {
          // We capture at 1.0 quality because EXPORT_PIXEL_RATIO is already handled inside IDCardPreview
          setFrontImage(frontCanvas.toDataURL('image/png', 1.0));
          setBackImage(backCanvas.toDataURL('image/png', 1.0));
        } else {
          console.error("Konva canvas not found in DOM");
        }
      } catch (err) {
        console.error("Capture error:", err);
        toast.error("Failed to capture high-res ID images");
      } finally {
        setIsGeneratingImages(false);
      }
    };

    captureKonvaStages();
  }, [data, layout]);

  const handleSilentPrint = async () => {
    if (!frontImage || !backImage) {
      toast.error('Processing images, please wait...');
      return;
    }

    const checkIsElectron = () => {
      const win = window as ExtendedWindow;
      return !!(win.process && win.process.type) || !!(win.navigator && win.navigator.userAgent.includes('Electron'));
    };

    if (checkIsElectron()) {
      try {
        // Mark as printed in database
        await confirmApplicant(data.id);
        
        const electron = (window as any).require('electron');
        const ipcRenderer = electron.ipcRenderer;

        ipcRenderer.send('print-card-images', {
          frontImage,
          backImage,
          width: PRINT_WIDTH,
          height: PRINT_HEIGHT,
          margins: {
            top: marginTop,
            bottom: marginBottom,
            left: marginLeft,
            right: marginRight,
          },
        });

        ipcRenderer.once('print-reply', (_event: any, arg: any) => {
          if (arg.success) {
            toast.success('Sent to printer successfully');
            setTimeout(onClose, 1000);
          } else {
            toast.error(`Print Error: ${arg.failureReason}`);
          }
        });
      } catch (err) {
        toast.error('Connection to local print service failed.');
      }
    } else {
      window.print();
    }
  };

  const totalWidth = PRINT_WIDTH + marginLeft + marginRight;
  const totalHeight = PRINT_HEIGHT + marginTop + marginBottom;

  return (
    <>
      <style>{`
        @media print {
          @page { margin: 0; size: 2.125in 3.375in portrait; }
          body * { visibility: hidden; }
          #print-root, #print-root * { visibility: visible; }
          #print-root { position: absolute; left: 0; top: 0; width: 100%; }
          .print-page {
            width: 2.125in !important;
            height: 3.375in !important;
            page-break-after: always !important;
            display: flex;
            align-items: center;
            justify-content: center;
          }
        }
        .hidden-stage { position: absolute; left: -9999px; top: -9999px; }
        .blueprint-bg {
          background-color: #0f172a;
          background-image: radial-gradient(#334155 1px, transparent 1px);
          background-size: 20px 20px;
        }
      `}</style>

      <div className="fixed inset-0 z-[100] flex bg-slate-950 text-slate-200">
        {/* Control Panel */}
        <aside className="w-96 h-full bg-slate-900 border-r border-slate-800 flex flex-col shadow-2xl">
          <div className="p-6 border-b border-slate-800 flex justify-between items-center">
            <h2 className="font-bold text-white">Print Terminal</h2>
            <button onClick={onClose} className="hover:bg-slate-800 p-1 rounded"><X size={20}/></button>
          </div>

          <div className="flex-1 overflow-y-auto p-6 space-y-8">
            {/* Margins */}
            <section className="space-y-4">
              <label className="text-xs font-bold text-slate-500 uppercase">Printer Offsets (Fine-tuning)</label>
              <div className="grid grid-cols-3 gap-2">
                {marginPresets.map(p => (
                  <button key={p.label} onClick={() => applyMarginPreset(p)} className="text-[10px] py-1 bg-slate-800 rounded">{p.label}</button>
                ))}
              </div>
              {[{l:'Top', v:marginTop, s:setMarginTop}, {l:'Right', v:marginRight, s:setMarginRight}, {l:'Bottom', v:marginBottom, s:setMarginBottom}, {l:'Left', v:marginLeft, s:setMarginLeft}].map(m => (
                <div key={m.l}>
                  <div className="flex justify-between text-[11px] mb-1"><span>{m.l} Offset</span><span>{m.v}px</span></div>
                  <input type="range" min="-50" max="50" value={m.v} onChange={(e)=>m.s(Number(e.target.value))} className="w-full accent-teal-500" />
                </div>
              ))}
            </section>

            {/* Mirroring */}
            <section className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase">Back Side Orientation</label>
              <button onClick={() => setMirrorBack(!mirrorBack)} className={`w-full p-3 rounded-lg border-2 flex items-center gap-3 transition-all ${mirrorBack ? 'border-teal-500 bg-teal-500/10' : 'border-slate-700'}`}>
                <FlipHorizontal size={18} />
                <span className="text-sm">Mirror Back Image</span>
              </button>
            </section>

            {/* Stats */}
            <div className="p-4 bg-slate-950 rounded border border-slate-800 text-[11px] font-mono space-y-1">
              <div className="flex justify-between text-slate-500"><span>Target Res:</span><span>{PRINT_WIDTH}x{PRINT_HEIGHT}</span></div>
              <div className="flex justify-between text-teal-400"><span>Final Feed:</span><span>{totalWidth}x{totalHeight}</span></div>
            </div>
          </div>

          <div className="p-6 bg-slate-950 border-t border-slate-800 space-y-3">
            <button 
              disabled={isGeneratingImages}
              onClick={handleSilentPrint} 
              className="w-full py-4 bg-teal-500 hover:bg-teal-400 disabled:bg-slate-700 text-slate-950 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg shadow-teal-500/20"
            >
              {isGeneratingImages ? <Loader2 className="animate-spin" /> : <Printer size={20} />}
              {isGeneratingImages ? 'Rasterizing ID...' : 'EXECUTE PRINT'}
            </button>
          </div>
        </aside>

        {/* Preview Area */}
        <main className="flex-1 blueprint-bg flex items-center justify-center p-12 overflow-auto">
          <div className="flex flex-col gap-8 transition-all duration-500" style={{ transform: `scale(${zoom})` }}>
            <div className="space-y-2">
              <IDCardPreview data={data} layout={layout} side="FRONT" scale={1} isPrinting={false} />
              <p className="text-center text-[10px] font-bold text-slate-500 uppercase tracking-widest">Front Perspective</p>
            </div>
            <div className="space-y-2" style={{ transform: mirrorBack ? 'scaleX(-1)' : 'none' }}>
              <IDCardPreview data={data} layout={layout} side="BACK" scale={1} isPrinting={false} />
              <p className="text-center text-[10px] font-bold text-slate-500 uppercase tracking-widest">Back Perspective</p>
            </div>
          </div>
        </main>
      </div>

      {/* HIDDEN RENDER STAGES 
          These use isPrinting={true} which triggers the PRINT_WIDTH/HEIGHT and 
          high pixelRatio defined in your IDCardPreview.
      */}
      <div className="hidden-stage">
        <div id="front-print-stage">
          <IDCardPreview data={data} layout={layout} side="FRONT" isPrinting={true} />
        </div>
        <div id="back-print-stage">
          <IDCardPreview data={data} layout={layout} side="BACK" isPrinting={true} />
        </div>
      </div>
    </>
  );
};

export default PrintPreviewModal;